version: "3.3"

networks:
  frontend2:
    ipam:
      config:
        - subnet: 173.20.0.0/24
services:
    kmaster11:
        image: pranay/ubuntu-sysd:2.0
        container_name: kmaster11
        hostname: kmaster11
        privileged: true
        networks:
            frontend2:
                ipv4_address: 173.20.0.27
        ports:
            - "5441:22"
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro 
        deploy:
          resources:
            limits:
              cpus: '2.0'
              memory: 4000M
        #command: ["systemctl","restart","ssh"]      


    kmaster12:
        image: pranay/ubuntu-sysd:2.0
        container_name: kmaster12
        hostname: kmaster22
        privileged: true
        networks:
            frontend2:
                ipv4_address: 173.20.0.28
        ports:
            - "5442:22"
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro 
        deploy:
          resources:
            limits:
              cpus: '2.0'
              memory: 4000M                

    control1:
        image: pranay/ubuntu-sysd:2.0
        container_name: control1
        hostname: control1
        privileged: true
        networks:
            frontend2:
                ipv4_address: 173.20.0.25
        ports:
            - "5440:22"
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        deploy:
          resources:
            limits:
              cpus: '1.0'
              memory: 2000M
 
